const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";
const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";
const USER_SIGNOUT_REQUEST = "USER_SIGNOUT_REQUEST";
const USER_SIGNOUT_SUCCESS = "USER_SIGNOUT_SUCCESS";
const USER_SIGNOUT_FAIL = "USER_SIGNOUT_FAIL";
const CREATE_USER_PROFILE_REQUEST = "CREATE_USER_PROFILE_REQUEST";
const CREATE_USER_PROFILE_SUCCESS = "CREATE_USER_PROFILE_SUCCESS";
const CREATE_USER_PROFILE_FAIL = "CREATE_USER_PROFILE_FAIL";
const GET_USER_PROFILE_REQUEST = "GET_USER_PROFILE_REQUEST";
const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
const GET_USER_PROFILE_FAIL = "GET_USER_PROFILE_FAIL";
const UPLOAD_IMAGE_REQUEST = "UPLOAD_IMAGE_REQUEST";
const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
const UPLOAD_IMAGE_FAIL = "UPLOAD_IMAGE_FAIL";
const UPDATE_USER_REQUEST = "UPLOAD_IMAGE_REQUEST";
const UPDATE_USER_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
const UPDATE_USER_FAIL = "UPLOAD_IMAGE_FAIL";
const RESET_USER_STATE = "RESET_USER_STATE";

export {
  USER_SIGNUP_REQUEST,
  USER_SIGNUP_SUCCESS,
  USER_SIGNUP_FAIL,
  USER_SIGNIN_REQUEST,
  USER_SIGNIN_SUCCESS,
  USER_SIGNIN_FAIL,
  USER_SIGNOUT_REQUEST,
  USER_SIGNOUT_SUCCESS,
  USER_SIGNOUT_FAIL,
  RESET_USER_STATE,
  CREATE_USER_PROFILE_REQUEST,
  CREATE_USER_PROFILE_SUCCESS,
  CREATE_USER_PROFILE_FAIL,
  GET_USER_PROFILE_REQUEST,
  GET_USER_PROFILE_SUCCESS,
  GET_USER_PROFILE_FAIL,
  UPLOAD_IMAGE_REQUEST,
  UPLOAD_IMAGE_SUCCESS,
  UPLOAD_IMAGE_FAIL,
  UPDATE_USER_REQUEST,
  UPDATE_USER_SUCCESS,
  UPDATE_USER_FAIL,
};
